spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sandeepdhamija/config-repo
          default-label: master
          clone-on-start: true
          timeout: 10
          force-pull: true

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5


